# Generated by Django 5.2 on 2025-04-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('contact_detalils', models.TextField()),
                ('bank_details', models.TextField()),
                ('shipping_policy', models.TextField()),
                ('return_policy', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
