# Generated by Django 5.2 on 2025-04-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
